version: "3.3"

services:
  db:
    image: postgres:14.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=payments
      - PG_DATA=/data
    volumes:
      - ./data:/data
    ports:
      - 5432:5432
